[project]
name = "cinemateca"
version = "0.1.0"
description = "Base de dados da cinemateca"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "scrapy>=2.12.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
